@startuml
skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide enum methods

package model {
    class Player {
        - username : String
        - isRobot : Boolean

        + <<create>> Player(name : String)
        + play(weapon : Weapon, x : Integer, y : Integer)
        + receiveAttack(s : Square, weapon : Weapon)
        + allBoatSinked() : Boolean
        + reset()
    }

    enum Orientation <<enumeration>> {
        VERTICAL
        HORIZONTAL
    }

    enum State <<enumeration>> {
        INTACT
        EMPTY
        SEARCHED
    }

    class Boat implements Content{
        - name : String
        - numberSquares : Integer
        - position : Integer[*]

        + <<create>> Boat(name : String, numberSquares : Integer)
        + isSinked() : Boolean
        + attacked(s : Square)
        + setPosition(x : Integer, y : Integer)
        + setOrientation(orientation : Orientation)
        + getPosition() : Integer[*]
    }

    class Square {
        - position : Integer[*]
        - attacked : Boolean
        - inIsland : Boolean

        + <<create>> Square(x : Integer, y : Integer, island : Boolean)
        + isEmpty() : Boolean
        + attack(weapon : Weapon) : ResultAttack
        + getContent() : Content
    }

    class Grid {
        - size : Integer

        + <<create>> Grid(size : Integer, mode : ModeGame)
        + placeBoat(b : Boat, x : Integer, y : Integer, orientation : Orientation)
        + placeTrap(t : Trap, x : Integer, y : Integer)
        + attack(x : Integer, y : Integer, weapon : Weapon) : ResultAttack
        + reset()
    }

    class Island {
        - position : Integer[*]
        - size : Integer

        + <<create>> Island(x : Integer, y : Integer, size : Integer, squares : Squares[*])
        + contains(s : Square) : Boolean
    }

    enum ModeGame <<enumeration>>{
        STANDARD
        ISLAND
    }

    abstract class Weapon <<abstract>> implements Content {
        - name : String
        - position : Integer[*]

        + <<create>> Weapon(name : String)
        + {abstract} use(grid : Grid, x : Integer, y : Integer) : ResultAttack
        + getPosition() : Integer[*]
    }

    class Missile extends Weapon {
        + use(grid : Grid, x : Integer, y : Integer) : ResultAttack
    }

    class Bomb extends Weapon {
        + use(grid : Grid, x : Integer, y : Integer) : ResultAttack
    }

    class Sonar extends Weapon {
        + use(grid : Grid, x : Integer, y : Integer) : ResultAttack
    }

    abstract class Trap <<abstract>> implements Content {
        - name : String
        - isActive : Boolean

        + <<create>> Trap(name : String)
        + getPosition() : Integer[*]
        + {abstract} trigger(assaillant : Player, defender : Player, c : Square) : Integer[*]
    }

    class BlackHole extends Trap {
        + <<create>> BlackHole(name : String)
        + trigger(assaillant : Player, defender : Player, c : Square) : Integer[*]
    }

    class Tornado extends Trap {
        - numberUse : Integer

        + <<create>> Tornado(name : String, numberUse : Integer)
        + trigger(assaillant : Player, defender : Player, c : Square) : Integer[*]
    }

    interface Content <<interface>> {
        + getPosition() : Integer[*]
    }

    class History {
        + <<create>> History()
        + addAction(action : Action)
        + getLast() : Action
        + reset()
    }

    class Action {
        - round : Integer
        - position : Integer[*]

        + <<create>> Action(round : Integer, x : Integer, y : Integer, player : Player, weapon : Weapon, result : ResultAttack)
    }

    class ResultAttack {
        - message : String

        + <<create>> ResultAttack(type : TypeResult, message : String)
    }

    enum TypeResult <<enumeration>> {
        FAILURE
        ATTACKED
        SINKED
        ISLAND
        TRAP
        SONAR_INFO
    }
}

package controller {

}

package views {

}

Player o-> "1\n- grid" Grid : > owns
Player o-> "1..*\n- weapons" Weapon : > owns
Player o-> "1..*\n- traps" Trap : > owns
Player o-> "1..*\n- boats" Boat : > owns
Boat o-> "1\n- orientation" Orientation : > is oriented
Boat *-> "1..*\n- squaresTaken" Square : > takes
Grid o-> "1..*\n- squares" Square : > contains
Grid o-> "1\n- ile" Island : > contains
Island *-> "1..*\n- squares" Square : > contains
Square *-> "1\n- content" Content : > contains
Square o-> "1\n- islandState" State : > is
History o-> "1\n- actions" Action : > has
Action *-> "1\n- player" Player
Action *-> "1\n- weapon" Weapon : > done with
Action o-> "1\n- result" ResultAttack : > results
ResultAttack o-> "1\n- type" TypeResult : > is

@enduml