@startuml
skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide enum methods

' Configuration de la mise en page
skinparam packageStyle rectangle
skinparam linetype ortho

' Espacement et taille
skinparam defaultFontSize 11
skinparam classAttributeFontSize 10
skinparam packageFontSize 12
skinparam packageFontStyle bold

' Espacement entre les packages
'top to bottom direction
left to right direction

package controller {
    class GameController {
        + <<create>> GameController()
        - configureGame() : GameConfig
        - placementGame() : GamePlacement
    }
}



controller.GameController o-> "1\n- currentGame" model.game.Game : > has

@enduml